### ISSUE TITLE
Enable programmatic access to schema

### ISSUE THREAD

**Issue by mhamann** [chrisandrews7/loopback-jsonschema-generator#1]
It would be useful to be able to access a model's json schema representation from the model itself without needing to resort to using a callback (i.e. `model.jsonSchema(...)`).

Would suggest either setting a model property, like `model.schema` or simply doing a `return schema` from the `jsonSchema()` method.

Thoughts?

**Comment by chrisandrews7** [comment]
@mhamann Agreed, good idea. Will get this included in the next release!

**Comment by chrisandrews7** [comment]
Sorry for the delay.
I've made the changes under - https://github.com/chrisandrews7/loopback-jsonschema-generator/pull/2

**Comment by chrisandrews7** [comment]
Released and available in npm - https://github.com/chrisandrews7/loopback-jsonschema-generator/releases/tag/1.1.1
